### ISSUE TITLE
UN85TU7000FXZC - Error log for first time connect

### ISSUE THREAD

**Issue by mrhhats** [bitfocus/companion-module-samsung-smarttv#8]
Hi there, running companion 3.1.2 on a Companion-PI. Can anyone shed light on this error? I have the TV ready and no notification ever pop up. The mac address gets discovered in a weird way. I remove it and put the actual mac address and no change.

any guidance would be super awesome!

error: 
error: /opt/companion-module-dev/companion-module-samsung-smarttv-main/node_modules/samsung-tv-control/lib/samsung.js:65
                throw new Error('Error send Key');
                ^

Error: Error send Key
    at /opt/companion-module-dev/companion-module-samsung-smarttv-main/node_modules/samsung-tv-control/lib/samsung.js:65:23
    at WebSocket.<anonymous> (/opt/companion-module-dev/companion-module-samsung-smarttv-main/node_modules/samsung-tv-control/lib/samsung.js:302:17)
    at WebSocket.emit (node:events:514:28)
    at WebSocket.emit (node:domain:489:12)
    at Receiver.receiverOnError (/opt/companion-module-dev/companion-module-samsung-smarttv-main/node_modules/ws/lib/websocket.js:1189:13)
    at Receiver.emit (node:events:514:28)
    at Receiver.emit (node:domain:489:12)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v18.17.1
Starting up module class: ModuleInstance
Sentry disabled
No token found in config, establishing first time connection?
Attempting connection to tv
Connection established
Samsung {
  IP: '10.20.7.14',
  MAC: ') at 00:09:0f:09:',
  PORT: 8002,
  APP_STRING: 'iphone..iapp.samsung',
  TV_APP_STRING: 'iphone.UE40NU7400.iapp.samsung',
  TOKEN: '',
  NAME_APP: 'Qml0Zm9jdXMgQ29tcGFuaW9u',
  LOGGER: Logger { DEBUG: false, LogFile: [] },
  SAVE_TOKEN: false,
  TOKEN_FILE: '/opt/companion-module-dev/companion-module-samsung-smarttv-main/node_modules/samsung-tv-control/lib/token.txt',
  WS_URL: 'wss://10.20.7.14:8002/api/v2/channels/samsung.remote.control?name=Qml0Zm9jdXMgQ29tcGFuaW9u'
`}`

<img width="1314" alt="image" src="https://github.com/bitfocus/companion-module-samsung-smarttv/assets/111146190/defe24bf-7f89-4537-bb42-8471104124ef">

<img width="655" alt="image" src="https://github.com/bitfocus/companion-module-samsung-smarttv/assets/111146190/8e5a316d-51b5-4b95-8c43-fd71f5ac9a61">

**Comment by matt-flaig** [comment]
Hi @mrhhats!

I haven't tested this module with the Companion-PI system image... perhaps I should do so!

Something strange is going on with MAC address discovery... but that may be a separate issue from the connectivity problem (as the MAC is only needed to turn the TV when connected via Ethernet with Wake-on-lan)... actually it does seem like the module believes that it is establishing a healthy connection with the TV (so perhaps the issue is just the access prompt is not showing up?).

Have you verified that your Samsung TV has Access Notifications enabled? (This is off by default on some TVs). The setting can probably be found under **Settings** > **General** > **External Device Manager** > **Device Connect Manager** > **Access Notification** is set to "First Time Only". If this setting was already enabled, try adding a token to the token field (something like 123457 will work just fine), and that may force the TV to show the access prompt again.

It might also be helpful to know what Samsung TV you're testing with... I've only tested with a few models (listed in the HELP.md file) so perhaps there's some incompatibility between other ones.

Cheers!

**Comment by mrhhats** [comment]
Hey! I got it going! my issue was more of an internal subnet problem. Thank you!
